# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_upload', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('school_id', models.UUIDField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('fileid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_attachments', to='file_upload.schoolimage')),
                ('voucher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='vouchers.voucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
