# Generated by Django 3.2.18 on 2023-12-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
        ('voucher_attachments', '0002_voucherattachment_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherattachment',
            name='voucher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='vouchers.voucher'),
        ),
    ]
