# Generated by Django 3.2.18 on 2024-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_term_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='academic_year',
            field=models.CharField(default='2023', max_length=255, null=True),
        ),
    ]
