# Generated by Django 3.2.18 on 2023-12-07 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0002_academicyear_is_current'),
        ('term', '0002_term_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academic_year.academicyear'),
        ),
    ]
