# Generated by Django 3.2.18 on 2023-12-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0003_alter_term_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='year',
        ),
    ]
