# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0001_initial'),
        ('term', '0001_initial'),
        ('classes', '0001_initial'),
        ('fee_structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(default=utils.currentAcademicYear, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fee_structures', to='academic_year.academicyear'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='classes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fee_structures', to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fee_structures', to='term.term'),
        ),
    ]
