# Generated by Django 3.2.18 on 2023-12-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_structures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='name',
        ),
    ]
