# Generated by Django 3.2.18 on 2023-12-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('term', '0001_initial'),
        ('fee_structures', '0002_alter_feestructure_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='classes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='term.term'),
        ),
    ]
