# Generated by Django 3.2.18 on 2023-12-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_structures', '0003_auto_20231204_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='fee_structure_values',
        ),
    ]
