# Generated by Django 3.2.18 on 2023-12-11 13:35

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0002_academicyear_is_current'),
        ('fee_structures', '0004_remove_feestructure_fee_structure_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(default=utils.currentAcademicYear, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academic_year.academicyear'),
        ),
    ]
