# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('companyName', models.CharField(default=None, max_length=255, null=True)),
                ('contactPerson', models.CharField(default=None, max_length=255, null=True)),
                ('phoneNumber', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.CharField(default=None, max_length=255, null=True)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('accountNo', models.CharField(default=None, max_length=255, null=True)),
                ('pinNo', models.CharField(default=None, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=7000, null=True)),
                ('school', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
