# Generated by Django 3.2.18 on 2023-12-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_cheque',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
