# Generated by Django 3.2.18 on 2023-12-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='school_id',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentmethods', to='school.school'),
        ),
    ]
