# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('payment_methods', '0002_paymentmethod_is_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentmethods', to='school.school'),
        ),
    ]
