# Generated by Django 3.2.18 on 2024-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0003_alter_paymentmethod_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_integration_default',
            field=models.BooleanField(default=False),
        ),
    ]
