# Generated by Django 3.2.18 on 2023-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0003_paymentmethod_dateofcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_bank',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_cash',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
