# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        ('academic_year', '0001_initial'),
        ('classes', '0001_initial'),
        ('term', '0001_initial'),
        ('schoolgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(default='BOY', max_length=6)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('boarding_status', models.CharField(default='BOARDING', max_length=255)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('invoice_Student', models.BooleanField(default=False, null=True)),
                ('current_Class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.classes')),
                ('current_Stream', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='streams.stream')),
                ('current_Term', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='term.term')),
                ('current_Year', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic_year.academicyear')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolgroups.schoolgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
