# Generated by Django 3.2.18 on 2023-11-29 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(default='BOY', max_length=6)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('boarding_status', models.CharField(default='BOARDING', max_length=255)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='streams.stream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
