# Generated by Django 3.2.18 on 2023-12-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('streams', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.AddField(
            model_name='student',
            name='current_Class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_Stream',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='streams.stream'),
        ),
    ]
