# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0001_initial'),
        ('streams', '0001_initial'),
        ('classes', '0001_initial'),
        ('term', '0001_initial'),
        ('schoolgroups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_Class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_Stream',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='streams.stream'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_Term',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='term.term'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_Year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='academic_year.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='schoolgroups.schoolgroup'),
        ),
    ]
