# Generated by Django 3.2.18 on 2023-12-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0001_initial'),
        ('students', '0002_auto_20231203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_Year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic_year.academicyear'),
        ),
    ]
