# Generated by Django 3.2.18 on 2024-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20231230_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
    ]
