# Generated by Django 3.2.18 on 2023-12-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_current_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='invoice_Student',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
