# Generated by Django 3.2.18 on 2024-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20240116_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
