# Generated by Django 3.2.18 on 2023-12-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
        ('students', '0004_student_invoice_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_Term',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='term.term'),
        ),
    ]
