# Generated by Django 3.2.18 on 2023-12-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolgroups', '0002_alter_schoolgroup_school_id'),
        ('students', '0005_student_current_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolgroups.schoolgroup'),
        ),
    ]
