# Generated by Django 3.2.18 on 2024-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
