# Generated by Django 3.2.18 on 2024-07-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0007_student_is_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_Class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.classes'),
        ),
    ]
