# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        ('students', '0001_initial'),
        ('academic_year', '0001_initial'),
        ('classes', '0001_initial'),
        ('currencies', '0001_initial'),
        ('voteheads', '0001_initial'),
        ('term', '0001_initial'),
        ('schoolgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uninvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(default='classes', max_length=255, null=True)),
                ('structure_class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('structure_stream', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
                ('structure_term', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('structure_year', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_year.academicyear')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innovation_document_creator', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(max_length=255)),
                ('classes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='classes.classes')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='schoolgroups.schoolgroup')),
                ('stream', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='streams.stream')),
                ('structure_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('structure_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('structure_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_year.academicyear')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('issueDate', models.CharField(max_length=255)),
                ('invoiceNo', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.CharField(max_length=255)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('classes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='classes.classes')),
                ('currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='currencies.currency')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student')),
                ('term', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='term.term')),
                ('votehead', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='voteheads.votehead')),
                ('year', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='academic_year.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('structure_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_year.academicyear')),
            ],
        ),
    ]
