# Generated by Django 3.2.18 on 2023-12-03 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_auto_20231203_2239'),
        ('term', '0001_initial'),
        ('currencies', '0002_alter_currency_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issueDate', models.CharField(max_length=255)),
                ('invoiceNo', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='currencies.currency')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student')),
                ('term', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='term.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
