# Generated by Django 3.2.18 on 2024-07-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_is_graduated'),
        ('invoices', '0002_auto_20231230_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='students.student'),
        ),
        migrations.AlterField(
            model_name='uninvoice',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innovation_document_creator', to='students.student'),
        ),
    ]
