# Generated by Django 3.2.18 on 2023-12-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
