# Generated by Django 3.2.18 on 2023-12-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
        ('classes', '0001_initial'),
        ('academic_year', '0001_initial'),
        ('invoices', '0003_alter_invoice_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='classes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='classes.classes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='academic_year.academicyear'),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(max_length=255)),
                ('structure_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('structure_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('structure_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_year.academicyear')),
            ],
        ),
    ]
