# Generated by Django 3.2.18 on 2023-12-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20231204_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceNo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
