# Generated by Django 3.2.18 on 2023-12-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_current_year'),
        ('streams', '0001_initial'),
        ('classes', '0001_initial'),
        ('invoices', '0005_alter_invoice_invoiceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='classes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='classes.classes'),
        ),
        migrations.AddField(
            model_name='structure',
            name='stream',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='streams.stream'),
        ),
        migrations.AddField(
            model_name='structure',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='students.student'),
        ),
    ]
