# Generated by Django 3.2.18 on 2023-12-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('academic_year', '0001_initial'),
        ('term', '0001_initial'),
        ('invoices', '0006_auto_20231204_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uninvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('structure_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('structure_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_year.academicyear')),
            ],
        ),
    ]
