# Generated by Django 3.2.18 on 2023-12-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_isdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='isDeleted',
        ),
    ]
