# Generated by Django 3.2.18 on 2023-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20231207_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uninvoice',
            name='invoice_who',
        ),
        migrations.AddField(
            model_name='uninvoice',
            name='filter_type',
            field=models.CharField(default='classes', max_length=255, null=True),
        ),
    ]
