# Generated by Django 3.2.18 on 2023-12-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0002_academicyear_is_current'),
        ('term', '0004_remove_term_year'),
        ('invoices', '0012_auto_20231211_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('structure_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_year.academicyear')),
            ],
        ),
    ]
