# Generated by Django 3.2.18 on 2023-12-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceNo',
            field=models.CharField(max_length=255),
        ),
    ]
