# Generated by Django 3.2.18 on 2023-11-29 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_head_name', models.CharField(max_length=255)),
                ('folio_number', models.CharField(max_length=255)),
                ('exempted', models.BooleanField(default=False)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteheads', to='account_types.accounttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
