# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteheadConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('configuration_type', models.CharField(choices=[('MANUAL', 'RATIO'), ('AUTO', 'AUTO')], max_length=10)),
                ('auto_configuration_type', models.CharField(blank=True, choices=[('PRIORITY', 'PRIORITY'), ('RATIO', 'RATIO')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('vote_head_name', models.CharField(max_length=255)),
                ('folio_number', models.CharField(default=1, max_length=255, null=True)),
                ('exempted', models.BooleanField(default=False)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('is_Overpayment_Default', models.BooleanField(default=False)),
                ('is_Arrears_Default', models.BooleanField(default=False)),
                ('priority_number', models.CharField(default=1, max_length=255)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteheads', to='account_types.accounttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
