# Generated by Django 3.2.18 on 2023-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='is_Overpayment_Default',
            field=models.BooleanField(default=False),
        ),
    ]
