# Generated by Django 3.2.18 on 2023-12-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='ledget_folio_number_lf',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
