# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_types', '0001_initial'),
        ('voteheads', '0002_votehead_ledget_folio_number_lf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votehead',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voteheads', to='account_types.accounttype'),
        ),
    ]
