# Generated by Django 3.2.18 on 2023-12-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0002_votehead_is_overpayment_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteheadConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('configuration_type', models.CharField(choices=[('MANUAL', 'RATIO'), ('AUTO', 'AUTO')], max_length=10)),
                ('auto_configuration_type', models.CharField(blank=True, choices=[('PRIORITY', 'PRIORITY'), ('RATIO', 'RATIO')], max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='votehead',
            name='priority_number',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='votehead',
            name='folio_number',
            field=models.CharField(default=1, max_length=255, null=True),
        ),
    ]
