# Generated by Django 3.2.18 on 2023-12-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0003_auto_20231214_1155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voteheadconfiguration',
            unique_together={('school_id',)},
        ),
    ]
