# Generated by Django 3.2.18 on 2023-12-14 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0004_alter_voteheadconfiguration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteheadconfiguration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='voteheadconfiguration',
            unique_together=set(),
        ),
    ]
