# Generated by Django 3.2.18 on 2023-12-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0005_auto_20231214_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteheadconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
