# Generated by Django 3.2.18 on 2024-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0005_alter_votehead_vote_head_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteheadconfiguration',
            name='configuration_type',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTO', 'AUTO')], max_length=10),
        ),
    ]
