# Generated by Django 3.2.18 on 2024-02-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0006_alter_voteheadconfiguration_configuration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votehead',
            name='folio_number',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='votehead',
            name='ledget_folio_number_lf',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='votehead',
            name='priority_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
