# Generated by Django 3.2.18 on 2023-12-14 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0006_alter_voteheadconfiguration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteheadconfiguration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
