# Generated by Django 3.2.18 on 2023-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0007_alter_voteheadconfiguration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='dateofcreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voteheadconfiguration',
            name='dateofcreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
