# Generated by Django 3.2.18 on 2023-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0008_auto_20231218_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='is_Arrears_Default',
            field=models.BooleanField(default=False),
        ),
    ]
