# Generated by Django 3.2.18 on 2024-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0008_auto_20240201_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='is_bursary_default',
            field=models.BooleanField(default=False),
        ),
    ]
