# Generated by Django 3.2.18 on 2023-12-09 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voteheads', '0002_votehead_is_overpayment_default'),
        ('receipts', '0006_auto_20231209_0826'),
        ('students', '0005_student_current_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('receipt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentinkinds', to='receipts.receipt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentinkinds', to='students.student')),
                ('votehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentinkinds', to='voteheads.votehead')),
            ],
        ),
    ]
