# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('voteheads', '0001_initial'),
        ('payment_in_kind_Receipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('itemName', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('receipt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentinkinds', to='payment_in_kind_Receipt.pikreceipt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentinkinds', to='students.student')),
                ('votehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentinkinds', to='voteheads.votehead')),
            ],
        ),
    ]
