# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_in_kind_Receipt', '0002_auto_20231230_1636'),
        ('voteheads', '0002_votehead_ledget_folio_number_lf'),
        ('students', '0001_initial'),
        ('payment_in_kinds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinkind',
            name='receipt',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentinkinds', to='payment_in_kind_Receipt.pikreceipt'),
        ),
        migrations.AlterField(
            model_name='paymentinkind',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentinkinds', to='students.student'),
        ),
        migrations.AlterField(
            model_name='paymentinkind',
            name='votehead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentinkinds', to='voteheads.votehead'),
        ),
    ]
