# Generated by Django 3.2.18 on 2023-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_in_kinds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinkind',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
