# Generated by Django 3.2.18 on 2023-12-16 13:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('staffNo', models.CharField(max_length=255)),
                ('phoneNo', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('emailAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('idNumber', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('TEACHING', 'TEACHING'), ('NON_TEACHING', 'NON_TEACHING')], default='TEACHING', max_length=255)),
                ('school', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
