# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_types', '0001_initial'),
        ('school_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, default='None', max_length=255)),
                ('city', models.CharField(default='None', max_length=255)),
                ('country', models.CharField(default='Kenya', max_length=255)),
                ('first_name', models.CharField(default='None', max_length=255)),
                ('last_name', models.CharField(default='None', max_length=255)),
                ('contact_fullname', models.CharField(blank=True, default='None', max_length=255)),
                ('contact_mobile', models.CharField(default='None', max_length=255)),
                ('contact_lastname', models.CharField(default='None', max_length=255)),
                ('contact_workphone', models.CharField(default='None', max_length=255)),
                ('postal_address', models.CharField(default='None', max_length=255)),
                ('postal_code', models.CharField(default='None', max_length=255)),
                ('schoolcode', models.CharField(default='None', max_length=255)),
                ('schoolgender', models.CharField(default='MIXED', max_length=255)),
                ('boardingstatus', models.CharField(default='MIXED', max_length=255)),
                ('school_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='school_categories.schoolcategory')),
                ('school_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='school_types.schooltype')),
            ],
        ),
    ]
