# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_types', '0001_initial'),
        ('school_categories', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schools', to='school_categories.schoolcategory'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schools', to='school_types.schooltype'),
        ),
    ]
