# Generated by Django 3.2.18 on 2023-12-07 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_student_current_term'),
        ('bank_accounts', '0001_initial'),
        ('currencies', '0002_alter_currency_currency_code'),
        ('academic_year', '0002_academicyear_is_current'),
        ('term', '0003_alter_term_year'),
        ('account_types', '0001_initial'),
        ('payment_methods', '0002_auto_20231206_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('receipt_date', models.DateField(auto_now_add=True, null=True)),
                ('receipt_No', models.CharField(max_length=255, null=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_code', models.CharField(max_length=255, null=True, unique=True)),
                ('addition_notes', models.TextField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='account_types.accounttype')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='bank_accounts.bankaccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='currencies.currency')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payment_methods.paymentmethod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='term.term')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='academic_year.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
