# Generated by Django 3.2.18 on 2024-07-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_is_graduated'),
        ('receipts', '0002_auto_20231230_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='students.student'),
        ),
    ]
