# Generated by Django 3.2.18 on 2023-12-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
    ]
