# Generated by Django 3.2.18 on 2023-12-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_rename_isdeleted_receipt_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='is_deleted',
            new_name='is_reversed',
        ),
        migrations.AddField(
            model_name='receipt',
            name='reversal_date',
            field=models.DateField(null=True),
        ),
    ]
