# Generated by Django 3.2.18 on 2023-12-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20231207_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='term',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='year',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='addition_notes',
            field=models.TextField(null=True),
        ),
    ]
