# Generated by Django 3.2.18 on 2023-12-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_auto_20231209_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
