# Generated by Django 3.2.18 on 2023-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_receipt_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='transaction_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
