# Generated by Django 3.2.18 on 2023-12-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0003_paymentmethod_dateofcreation'),
        ('receipts', '0011_alter_receipt_addition_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payment_methods.paymentmethod'),
        ),
    ]
