# Generated by Django 3.2.18 on 2023-12-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_alter_receipt_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='counter',
            field=models.IntegerField(auto_created=True, default=None, null=True),
        ),
    ]
