# Generated by Django 3.2.18 on 2023-12-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0003_financialyear_is_current'),
        ('receipts', '0013_receipt_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='financial_years.financialyear'),
        ),
    ]
