# Generated by Django 3.2.18 on 2023-12-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
