# Generated by Django 3.2.18 on 2024-01-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='overall_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='voteheadamounts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
