# Generated by Django 3.2.18 on 2023-12-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_auto_20231206_1943'),
        ('bursaries', '0002_auto_20231213_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='unposted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bursary',
            name='unposted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='paymentMethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='payment_methods.paymentmethod'),
        ),
    ]
