# Generated by Django 3.2.18 on 2024-01-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_auto_20240114_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='counter',
            field=models.FloatField(default=None, null=True),
        ),
    ]
