# Generated by Django 3.2.18 on 2023-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0004_rename_unposted_bursary_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='posted',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
