# Generated by Django 3.2.18 on 2024-01-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0002_financialyear_previous_financial_year'),
        ('grants', '0004_grant_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grants', to='financial_years.financialyear'),
        ),
    ]
