# Generated by Django 3.2.18 on 2024-01-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_grant_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='assigned_voteheadamounts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
