# Generated by Django 3.2.18 on 2023-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0005_alter_bursary_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='unposted_date',
            field=models.DateField(null=True),
        ),
    ]
