# Generated by Django 3.2.18 on 2024-01-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_grant_assigned_voteheadamounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='overall_amount',
            new_name='total_amount',
        ),
    ]
