# Generated by Django 3.2.18 on 2024-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_rename_overall_amount_grant_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='overall_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
