# Generated by Django 3.2.18 on 2024-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0009_auto_20240201_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='students',
            field=models.JSONField(default=list, null=True),
        ),
    ]
