# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolgroups', '0001_initial'),
        ('fee_structures', '0001_initial'),
        ('voteheads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('boardingStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('school_id', models.UUIDField(blank=True, default=None, null=True)),
                ('fee_Structure', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='fee_structures.feestructure')),
                ('school_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='schoolgroups.schoolgroup')),
                ('votehead', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='voteheads.votehead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
