# Generated by Django 3.2.18 on 2023-12-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_structures', '0002_remove_feestructure_name'),
        ('fee_structures_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructureitem',
            name='fee_structure_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures_items', to='fee_structures.feestructure'),
        ),
    ]
