# Generated by Django 3.2.18 on 2024-07-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolgroups', '0001_initial'),
        ('fee_structures', '0003_auto_20240718_1008'),
        ('voteheads', '0009_votehead_is_bursary_default'),
        ('fee_structures_items', '0002_auto_20231230_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructureitem',
            name='fee_Structure',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='fee_structures.feestructure'),
        ),
        migrations.AlterField(
            model_name='feestructureitem',
            name='school_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='schoolgroups.schoolgroup'),
        ),
        migrations.AlterField(
            model_name='feestructureitem',
            name='votehead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_items', to='voteheads.votehead'),
        ),
    ]
