# Generated by Django 3.2.18 on 2023-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_structures_items', '0002_auto_20231204_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructureitem',
            name='dateofcreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
