# Generated by Django 3.2.18 on 2023-11-29 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('school', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
