# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0002_auto_20231230_1636'),
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bursary',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='bursaries.bursary'),
        ),
        migrations.AlterField(
            model_name='item',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='students.student'),
        ),
        migrations.AlterField(
            model_name='item',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='classes.classes'),
        ),
    ]
