# Generated by Django 3.2.18 on 2023-12-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
