# Generated by Django 3.2.18 on 2024-01-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaconfig',
            name='is_saved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
