# Generated by Django 3.2.18 on 2024-01-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_configs', '0002_alter_mpesaconfig_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesaconfig',
            name='callback_url',
            field=models.CharField(blank=True, default='https://tafatalk.co.ke/api/v1/payments/callback', max_length=255, null=True),
        ),
    ]
