# Generated by Django 3.2.18 on 2024-01-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_configs', '0004_mpesaconfig_paybill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesaconfig',
            name='registration_url',
            field=models.CharField(blank=True, default='https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mpesaconfig',
            name='token_url',
            field=models.CharField(blank=True, default='https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials', max_length=255, null=True),
        ),
    ]
