# Generated by Django 3.2.18 on 2023-12-07 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voteheads', '0001_initial'),
        ('payment_methods', '0002_auto_20231206_1943'),
        ('academic_year', '0002_academicyear_is_current'),
        ('account_types', '0001_initial'),
        ('students', '0005_student_current_term'),
        ('term', '0003_alter_term_year'),
        ('currencies', '0002_alter_currency_currency_code'),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('addition_notes', models.TextField()),
                ('receipt_no', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='account_types.accounttype')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='bank_accounts.bankaccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='currencies.currency')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='payment_methods.paymentmethod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='term.term')),
                ('votehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='voteheads.votehead')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='academic_year.academicyear')),
            ],
        ),
    ]
