# Generated by Django 3.2.18 on 2023-12-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='school_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
