# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('voteheads', '0002_votehead_ledget_folio_number_lf'),
        ('students', '0001_initial'),
        ('appcollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='receipt',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections', to='students.student'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='votehead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections', to='voteheads.votehead'),
        ),
    ]
