# Generated by Django 3.2.18 on 2023-12-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcollections', '0002_collection_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='addition_notes',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='receipt_no',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='term',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='year',
        ),
    ]
