# Generated by Django 3.2.18 on 2023-12-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('appcollections', '0003_auto_20231207_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='receipt',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
