# Generated by Django 3.2.18 on 2023-12-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcollections', '0004_auto_20231207_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_overpayment',
            field=models.BooleanField(default=False),
        ),
    ]
