# Generated by Django 3.2.18 on 2023-12-16 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_in_kind_Receipt', '0001_initial'),
        ('appcollections', '0005_collection_is_overpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='pikReceipt',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='payment_in_kind_Receipt.pikreceipt'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_overpayment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
