# Generated by Django 3.2.18 on 2023-12-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcollections', '0006_auto_20231216_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='pikReceipt',
        ),
    ]
