# Generated by Django 3.2.18 on 2024-01-11 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrantItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('item_date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('school_id', models.UUIDField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
