# Generated by Django 3.2.18 on 2024-01-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_items', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantitem',
            name='votehead',
        ),
    ]
