# Generated by Django 3.2.18 on 2024-01-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0003_alter_votehead_account_type'),
        ('grant_items', '0003_remove_grantitem_votehead'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantitem',
            name='votehead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grant_items', to='voteheads.votehead'),
        ),
    ]
