# Generated by Django 3.2.18 on 2023-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
