# Generated by Django 3.2.18 on 2024-01-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
