# Generated by Django 3.2.18 on 2024-01-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0002_alter_academicyear_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year',
            field=models.CharField(max_length=255),
        ),
    ]
