# Generated by Django 3.2.18 on 2023-12-06 03:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0003_auto_20231206_0627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolImages',
            new_name='SchoolImage',
        ),
    ]
