# Generated by Django 3.2.18 on 2023-12-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_rename_schoolimages_schoolimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
