# Generated by Django 3.2.18 on 2023-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_schoolimage_dateofcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolimage',
            name='title',
            field=models.CharField(blank=True, default='Ttitle', max_length=255, null=True, unique=True),
        ),
    ]
