# Generated by Django 3.2.18 on 2023-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_alter_schoolimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolimage',
            name='title',
            field=models.CharField(blank=True, default='Ttitle', max_length=255, null=True),
        ),
    ]
