# Generated by Django 3.2.18 on 2023-12-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='date_created',
            new_name='date_deleted',
        ),
    ]
