# Generated by Django 3.2.18 on 2023-12-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_categories', '0002_expensecategory_dateofcreation'),
        ('vouchers', '0005_auto_20231221_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expenseCategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='expense_categories.expensecategory'),
        ),
    ]
