# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_id', to='school.school'),
        ),
    ]
