# Generated by Django 3.2.18 on 2024-01-20 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('bursary_start_at', models.IntegerField(default=0.0)),
                ('grant_start_at', models.IntegerField(default=0.0)),
                ('receipt_start_at', models.IntegerField(default=0.0)),
                ('voucher_start_at', models.IntegerField(default=0.0)),
                ('school', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
