# Generated by Django 3.2.18 on 2024-01-29 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account_types', '0001_initial'),
        ('financial_years', '0002_financialyear_previous_financial_year'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('budget_items', models.JSONField(blank=True, default=list, null=True)),
                ('accountType', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='account_types.accounttype')),
                ('financialYear', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='financial_years.financialyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
