# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('financial_year_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school', models.UUIDField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
