# Generated by Django 3.2.18 on 2023-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0002_financialyear_dateofcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='is_current',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
