# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0003_alter_votehead_account_type'),
        ('voucher_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheritem',
            name='votehead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voucher_items', to='voteheads.votehead'),
        ),
    ]
