# Generated by Django 3.2.18 on 2023-12-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vouchers', '0001_initial'),
        ('voucher_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='voucher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_items', to='vouchers.voucher'),
        ),
    ]
