# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_methods', '0001_initial'),
        ('academic_year', '0001_initial'),
        ('bank_accounts', '0001_initial'),
        ('currencies', '0001_initial'),
        ('term', '0001_initial'),
        ('schoolgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('transactionNumber', models.CharField(default=None, max_length=255)),
                ('receipientAddress', models.CharField(default=None, max_length=255)),
                ('institution', models.CharField(default=None, max_length=255)),
                ('institutionAddress', models.CharField(default=None, max_length=255)),
                ('school_id', models.UUIDField(blank=True, default=None, null=True)),
                ('posted', models.BooleanField(default=False, null=True)),
                ('unposted_date', models.DateField(null=True)),
                ('receipt_date', models.DateField(default=None, null=True)),
                ('studentamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('bankAccount', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='bank_accounts.bankaccount')),
                ('currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='currencies.currency')),
                ('paymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='payment_methods.paymentmethod')),
                ('schoolgroup', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='schoolgroups.schoolgroup')),
                ('term', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='term.term')),
                ('year', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='academic_year.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
