# Generated by Django 3.2.18 on 2023-12-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('payment_methods', '0002_auto_20231206_1943'),
        ('term', '0004_remove_term_year'),
        ('bursaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='bankAccount',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='bank_accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='institution',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='institutionAddress',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='payment_methods.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='receipientAddress',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='school_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='term',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='term.term'),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='transactionNumber',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
