# Generated by Django 3.2.18 on 2023-12-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0003_auto_20231215_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bursary',
            old_name='unposted',
            new_name='posted',
        ),
    ]
