# Generated by Django 3.2.18 on 2024-02-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0004_bursary_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursary',
            name='total_amount',
        ),
    ]
