# Generated by Django 3.2.18 on 2023-12-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0006_alter_bursary_unposted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='posted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
