# Generated by Django 3.2.18 on 2024-02-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteheads', '0009_votehead_is_bursary_default'),
        ('bursaries', '0007_bursary_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='votehead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bursaries', to='voteheads.votehead'),
        ),
    ]
