# Generated by Django 3.2.18 on 2023-12-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0008_bursary_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='receipt_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
