# Generated by Django 3.2.18 on 2023-12-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolgroups', '0003_schoolgroup_dateofcreation'),
        ('bursaries', '0010_bursary_dateofcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='schoolgroup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='schoolgroups.schoolgroup'),
        ),
        migrations.AddField(
            model_name='bursary',
            name='studentamount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
