# Generated by Django 3.2.18 on 2023-12-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currency_dateofcreation'),
        ('bursaries', '0011_auto_20231218_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='currencies.currency'),
        ),
    ]
