# Generated by Django 3.2.18 on 2023-12-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0013_bursary_financial_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bursary',
            name='financial_year',
        ),
    ]
