# Generated by Django 3.2.18 on 2023-12-09 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0002_alter_currency_currency_code'),
        ('students', '0005_student_current_term'),
        ('bank_accounts', '0001_initial'),
        ('voteheads', '0002_votehead_is_overpayment_default'),
        ('academic_year', '0002_academicyear_is_current'),
        ('term', '0003_alter_term_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIKReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('receipt_date', models.DateField(auto_now_add=True, null=True)),
                ('receipt_No', models.CharField(max_length=255, null=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('addition_notes', models.TextField(null=True)),
                ('is_posted', models.BooleanField(blank=True, default=True)),
                ('unposted_date', models.DateField(null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='bank_accounts.bankaccount')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='currencies.currency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='students.student')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='term.term')),
                ('votehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='voteheads.votehead')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='academic_year.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
