# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_years', '0001_initial'),
        ('students', '0001_initial'),
        ('academic_year', '0001_initial'),
        ('classes', '0001_initial'),
        ('bank_accounts', '0001_initial'),
        ('currencies', '0001_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIKReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('receipt_date', models.DateField(auto_now_add=True, null=True)),
                ('receipt_No', models.CharField(max_length=255, null=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('addition_notes', models.CharField(blank=True, max_length=7000, null=True)),
                ('is_posted', models.BooleanField(blank=True, default=True)),
                ('unposted_date', models.DateField(null=True)),
                ('overpayment_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('counter', models.FloatField(default=None, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='bank_accounts.bankaccount')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='currencies.currency')),
                ('financial_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='financial_years.financialyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='students.student')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='classes.classes')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='term.term')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pik_receipts', to='academic_year.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
