# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('academic_year', '0001_initial'),
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('financial_years', '0002_financialyear_previous_financial_year'),
        ('term', '0001_initial'),
        ('bank_accounts', '0002_auto_20231230_1636'),
        ('payment_in_kind_Receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikreceipt',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pik_receipts', to='bank_accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='pikreceipt',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pik_receipts', to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='pikreceipt',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pik_receipts', to='financial_years.financialyear'),
        ),
        migrations.AlterField(
            model_name='pikreceipt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pik_receipts', to='students.student'),
        ),
        migrations.AlterField(
            model_name='pikreceipt',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pik_receipts', to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='pikreceipt',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pik_receipts', to='term.term'),
        ),
        migrations.AlterField(
            model_name='pikreceipt',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pik_receipts', to='academic_year.academicyear'),
        ),
    ]
