# Generated by Django 3.2.18 on 2023-12-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_in_kind_Receipt', '0002_pikreceipt_student_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pikreceipt',
            name='votehead',
        ),
    ]
