# Generated by Django 3.2.18 on 2023-12-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_in_kind_Receipt', '0005_alter_pikreceipt_addition_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikreceipt',
            name='overpayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
