# Generated by Django 3.2.18 on 2023-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_in_kind_Receipt', '0006_pikreceipt_overpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikreceipt',
            name='counter',
            field=models.IntegerField(auto_created=True, default=None, null=True),
        ),
    ]
