# Generated by Django 3.2.18 on 2023-12-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_in_kind_Receipt', '0008_pikreceipt_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikreceipt',
            name='counter',
            field=models.FloatField(default=None, null=True),
        ),
    ]
