# Generated by Django 3.2.18 on 2023-12-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('votehead_name', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTransactionsPrintView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('transactionDate', models.CharField(blank=True, max_length=20, null=True)),
                ('transactionType', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('expected', models.CharField(blank=True, max_length=20, null=True)),
                ('paid', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportStudentBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('boarding_status', models.CharField(default='BOARDING', max_length=255)),
                ('expected', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('totalBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('schoolFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('current_Class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportStudentBalance', to='classes.classes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivedCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactionDate', models.CharField(blank=True, max_length=20, null=True)),
                ('dateofcreation', models.CharField(blank=True, max_length=20, null=True)),
                ('chequeNo', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
