# Generated by Django 3.2.18 on 2023-12-17 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStudentBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('boarding_status', models.CharField(default='BOARDING', max_length=255)),
                ('expected', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('totalBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('schoolFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('current_Class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportStudentBalance', to='classes.classes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
