# Generated by Django 3.2.18 on 2023-12-17 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reportss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransactionsPrintView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactionDate', models.CharField(blank=True, max_length=20, null=True)),
                ('transactionType', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('expected', models.CharField(blank=True, max_length=20, null=True)),
                ('paid', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
