# Generated by Django 3.2.18 on 2023-12-27 01:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial_years', '0001_initial'),
        ('reportss', '0002_balancetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningClosingBalances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('school_id', models.UUIDField(blank=True, null=True)),
                ('balanceAfter', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_cash_at_hand', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_cash_at_bank', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('closing_cash_at_hand', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('closing_cash_at_bank', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('financial_year', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_years.financialyear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
