# Generated by Django 3.2.18 on 2023-12-18 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reportss', '0002_studenttransactionsprintview'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('votehead_name', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
