# Generated by Django 3.2.18 on 2023-12-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportss', '0003_openingclosingbalances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingclosingbalances',
            name='balanceAfter',
        ),
    ]
