# Generated by Django 3.2.18 on 2023-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportss', '0003_incomesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesummary',
            name='dateofcreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reportstudentbalance',
            name='dateofcreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttransactionsprintview',
            name='dateofcreation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
