# Generated by Django 3.2.18 on 2023-12-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('financial_years', '0002_financialyear_previous_financial_year'),
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('reportss', '0004_remove_openingclosingbalances_balanceafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetracker',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AlterField(
            model_name='openingclosingbalances',
            name='financial_year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='financial_years.financialyear'),
        ),
        migrations.AlterField(
            model_name='receivedcheque',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='receivedcheque',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
        migrations.AlterField(
            model_name='reportstudentbalance',
            name='current_Class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reportStudentBalance', to='classes.classes'),
        ),
    ]
