# Generated by Django 3.2.18 on 2023-12-18 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currency_dateofcreation'),
        ('students', '0007_student_dateofcreation'),
        ('reportss', '0004_auto_20231218_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactionDate', models.CharField(blank=True, max_length=20, null=True)),
                ('dateofcreation', models.CharField(blank=True, max_length=20, null=True)),
                ('chequeNo', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
