# Generated by Django 3.2.18 on 2024-07-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_is_graduated'),
        ('reportss', '0005_auto_20231230_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetracker',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='receivedcheque',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
